search_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('searching.urls','searching'), namespace='searching'))
]

searching/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search')
]

searching/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=70)
    content = models.TextField()
    source = models.CharField(max_length=50)
    time = models.DateTimeField()
    url = models.CharField(max_length=50)
    def __str__(self):
        return self.title

searching/views.py
from django.db.models import Q
from django.shortcuts import render
import dateutil.parser
from .models import Post
import searching.engine.dataloader
from searching.engine.algorithm import tools

tool = tools()
tool.init()

def index(request):
    return render(request,'base.html')

def search(request):
    key = request.GET.get('key')
    group = request.GET.get('group')
    cate = request.GET.get('category')
    error_msg = ''
    if not key:
        error_msg = "请输入关键词"
        return render(request, 'index.html', {'error_msg': error_msg})

    if group == '1':
        bq = tool.rankedQuery(key, 15)
    elif group == '3':
        print(tool.termDict)
        bq = tool.booleanQuery(key.split())
    else:
        bq = tool.specificQuery(dateutil.parser.parse(key))

    print(bq)
    post_list = []
    for i in bq:
        if cate=='0':
            post_list.append(tool.docs[i])
        else:
            if (tool.docs[i]['label'] + 1) == int(cate):
                post_list.append(tool.docs[i])

    # post_list = Post.objects.filter(Q(title__icontains=key) | Q(content__icontains=key))
    return render(request, 'index.html', {'error_msg': error_msg, 'post_list': post_list})

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<style type="text/css">

			form .text {
				display: inline-block;
				border: 0;
				width: 260px;
				height: 35px;
				font-size: 14px;
				outline: none;

				border: 2px solid #01af63;
			}

			form .search {

				width: 90px;
				height: 38px;
				border: 0;
				outline: none;
				cursor: pointer;
				/*   cursor: pointer;   鼠标悬停或点击时button时鼠标变成其他图标  */
				text-align: center;
				line-height: 40px;
				background-color: #01af63;
				color: #FFFFFF;
			}

            form .limitMultiLine{
		        display: -webkit-box;
		        -webkit-line-clamp: 2;
		        -webkit-box-orient: vertical;
		        text-overflow: ellipsis;
		        overflow: hidden;
	        }
		</style>
	</head>
	<body>

		<form action={% url 'searching:search' %}>
			<input type="text" placeholder="Please input keywords" name="key" class="text" required />
			<input type="submit" value="Search" class="search">
            <select name="group" value="1">
                <option value="1">ranked query</option>
                <option value="2">time query</option>
                <option value="3">boolean query</option>
<!--                <option value="4">Sports</option>-->
<!--                <option value="5">Others</option>-->
            </select>


            <select name="category" value="0">
                <option value="0">All</option>
                <option value="1">Politics</option>
                <option value="2">Science and Sports</option>
                <option value="3">Daily Life</option>
                <option value="4">Business</option>
<!--                <option value="4">Sports</option>-->
<!--                <option value="5">Others</option>-->
            </select>

		</form>
	</body>
</html>

templates/index.html

<style type="text/css">
            .limitMultiLine{
		        display: -webkit-box;
		        -webkit-line-clamp: 2;
		        -webkit-box-orient: vertical;
		        text-overflow: ellipsis;
		        overflow: hidden;
	        }
</style>
{% block main %}
<head>
		<title></title>
    <style type="text/css">
            form .limitMultiLine{
		        display: -webkit-box;
		        -webkit-line-clamp: 2;
		        -webkit-box-orient: vertical;
		        text-overflow: ellipsis;
		        overflow: hidden;
	        }
</style>
</head>
	{% if error_msg %}
		<p>{{ error_msg }}</p>
	{% endif %}


	{% for post in post_list %}
	    <div>
        <a href="{{ post.url }}"><font color="red">{{post.title}}</font> </a>
        <p class="limitMultiLine">
            {{post.content}}
        </p>
        </div>
	{% empty %}
		<div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
{% endblock main %}